### ISSUE TITLE
Possibility to supply a GlyphIcon as symbol

### ISSUE THREAD

**Issue by johnsirach** [HanSolo/regulators#1]
Jens deters has a project called fontawesomefx (https://bitbucket.org/Jerady/fontawesomefx) which gives the possibility to use various font icons within JavaFX. It would be very nice to have a (set)symbol (builder) method added which gives the possibility to use a GlyphIcon as symbol.

Cheers,
John.

P.S. Keep up the awesome work, will be implementing this and other libraries (medusa) soon.

**Comment by HanSolo** [comment]
I've added support for the Ikonli library instead. You can find more info about it here
- source              : https://github.com/aalmiray/ikonli
- binary               : https://bintray.com/aalmiray/kordamp/ikonli/view#
- documentation : http://aalmiray.github.io/ikonli/#_materialdesign
  It has even more icons and is easier to implement. I've added the following icon packs already:
- fontawesome-pack:1.6.0
- material-pack:1.6.0
- materialdesign-pack:1.6.0
- weathericons-pack:1.6.0
  If you need more, just add the dependency of the package to your project and you can set the Icon by using the setIcon() method of either the Regulator or FeedbackRegulator.
  I've updated the Main.class so that you can see how to use the icons.

**Comment by johnsirach** [comment]
That's quick! Will try later today or tomorrow as i need to compile ikonli with retrolambda support if needed as it is being used within javafxports to create android mobile builds.
